version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pytest
    versions:
    - ">= 5.a, < 6"
  - dependency-name: setuptools
    versions:
    - 53.1.0
