sudo: required
language: python

services:
  - docker

before_install:
  - docker-compose -f docker-compose.yml -f docker-compose.ci.yml build

script:
  - docker-compose -f docker-compose.yml -f docker-compose.ci.yml run sciencebeam-alignment ./project_tests.sh

